---

env:
  global: 625009ae3209eeb8c3f1dfd997ff7bfef0e767e7c153c6130f4913cdebd2366d

language: node_js

node_js:
  - stable

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test
  - make testCoverage

after_script:
  - ./cc-test-reporter after-build -r 625009ae3209eeb8c3f1dfd997ff7bfef0e767e7c153c6130f4913cdebd2366d after-build < coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
